// Real micrographs for the label cards, all from Wikimedia Commons (public domain,
// CC0, CC BY or CC BY-SA). Licence and author are as Commons records them (checked
// 2026-09-30, and 2026-10-05 for the fission yeast, E. coli, Golgi, centrosome, plant, virus and Aspergillus images); every image was looked at to confirm the caption. Where no image of the
// right organism exists, the caption says what is shown instead. Files are 640 px
// copies in public/micrographs.

import type { CellTypeId, Micrograph } from '../contracts';

type Pic = Omit<Micrograph, 'src'>;

const PICS: Record<string, Pic> = {
  // added 2026-10-05 for the animal cell, plant cell, Aspergillus hypha and the two viruses
  'chloroplast-tem': { commons: 'File:Chloroplast in leaf of Anemone sp TEM 12000x.png', author: 'and3k and caper437', license: 'CC BY-SA 3.0', modality: 'TEM',
    caption: 'A chloroplast in a leaf cell of an anemone, in thin section: the dark stacked membranes are the thylakoids that carry chlorophyll. It lies pressed against the cell wall (top), with the vacuole below.' },
  'moss-chloroplasts': { commons: 'File:Bryum capillare leaf cells showing chloroplasts.jpg', author: 'Des_Callaghan', license: 'CC BY-SA 4.0', modality: 'Light',
    caption: 'Living leaf cells of the moss Bryum capillare. The pale lines between the cells are their walls; the green bodies are chloroplasts.' },
  'elodea-cells': { commons: 'File:Chloroplasts - Microscopic view of Elodea canadensis.jpg', author: 'Juan Carlos Fonseca Mata', license: 'CC BY-SA 4.0', modality: 'Light',
    caption: 'Leaf cells of the waterweed Elodea canadensis. Each brick-shaped cell is mostly vacuole, which is clear; the chloroplasts lie in the thin layer of cytoplasm around it.' },
  'palisade-sem': { commons: 'File:Tobacco mesophyll cryofracture in electron microscopy 1.tif', author: 'Juan de Dios Franco Navarro', license: 'CC BY 4.0', modality: 'SEM',
    caption: 'A tobacco leaf frozen and broken across, seen edge-on in the scanning electron microscope: the mesophyll cells stand packed between its two surfaces. Scale bar 100 µm.' },
  'rough-er': { commons: 'File:Mammalian pancreatic tissue, nuclear pores and rough endoplasmic reticulum.jpg', author: 'Louisa Howard', license: 'Public domain', modality: 'TEM',
    caption: 'A pancreatic acinar cell in thin section: parallel sheets of rough ER (left and top) beside the nucleus, whose envelope shows its pores. Scale bar 500 nm.' },
  'club-cell-tem': { commons: 'File:Clara cell lung - TEM.jpg', author: 'Louisa Howard', license: 'Public domain', modality: 'TEM',
    caption: 'A secretory (club) cell of the mammalian lung in thin section: the nucleus with its dark nucleolus at lower right, stacked rough ER above it and mitochondria at the left. Scale bar 500 nm.' },
  'peroxisomes': { commons: 'File:Peroxisome in rat neonatal cardiomyocyte.jpg', author: 'Evgeniy Ukraine', license: 'CC BY-SA 4.0', modality: 'Fluorescence',
    caption: 'Peroxisomes in rat heart muscle cells, stained for the peroxisomal membrane protein PMP70: hundreds of small dots in each cell.' },
  'cell-membranes-tem': { commons: 'File:Desmosome - epithelial cell from mammalian lung tissue - TEM.jpg', author: 'Louisa Howard', license: 'Public domain', modality: 'TEM',
    caption: 'The plasma membranes of two neighbouring lung epithelial cells running side by side, in thin section; the dense stretch is a desmosome that rivets them together. Scale bar 100 nm.' },
  't4-shadowed': { commons: 'File:Bacteriophage.jpg', author: 'AFADadcADSasd', license: 'CC BY 4.0', modality: 'TEM',
    caption: 'Two bacteriophage T4 particles, metal-shadowed for the electron microscope: the faceted head, the tail and the baseplate with its fibres.' },
  't4-em': { commons: 'File:T4 phage EM.jpg', author: '7USSR7', license: 'CC BY 4.0', modality: 'TEM',
    caption: 'One T4 particle in negative stain: head, striated tail sheath, baseplate and the long tail fibres spread out from it.' },
  't4-field': { commons: 'File:Viruses-07-02932-g002B-T4.png', author: 'Šimoliūnas et al., Viruses (2015)', license: 'CC BY 4.0', modality: 'TEM',
    caption: 'Purified phage particles in negative stain; those marked 1 are T4, beside a smaller phage (2). Scale bar 200 nm.' },
  'sars2-virions': { commons: 'File:Novel Coronavirus SARS-CoV-2 (49640655213).jpg', author: 'NIAID', license: 'CC BY 2.0', modality: 'TEM',
    caption: 'Three SARS-CoV-2 particles isolated from a patient (transmission electron micrograph, colourised): the spikes stand out from the envelope as a fringe.' },
  'sars2-cell': { commons: 'File:Novel Coronavirus SARS-CoV-2 (49597020718).jpg', author: 'NIAID', license: 'CC BY 2.0', modality: 'TEM',
    caption: 'SARS-CoV-2 particles (red, colourised) in thin section, in and around a cell: each is a membrane around a dense core of RNA and protein.' },
  'aspergillus-tip': { commons: 'File:Localization of the Aspergillus nidulans myosin V (MyoE) at the hyphal growth tip - journal.pone.0031218.g004H.png', author: 'Taheri-Talesh N, Xiong Y, Oakley BR (2012)', license: 'CC BY 2.5', modality: 'Fluorescence',
    caption: 'The tip of a living Aspergillus nidulans hypha. A myosin motor (green) and a vesicle protein (red) meet in the bright spot at the apex, the Spitzenkörper. Scale bar 5 µm.' },
  'aspergillus-septate': { commons: 'File:Aspergillus hyphae in LPCB tease mount of culture microscopy.jpg', author: 'Ajay Kumar Chaurasiya', license: 'CC BY-SA 4.0', modality: 'Light',
    caption: 'Branched hyphae of an Aspergillus, stained with lactophenol cotton blue: the cross-lines along each tube are septa.' },
  'aspergillus-mycelium': { commons: 'File:Aspergillus niger hyphae.jpg', author: 'Y_tambe', license: 'CC BY-SA 3.0', modality: 'Light',
    caption: 'A week-old colony of Aspergillus niger seen from the side: hyphae growing down into the agar (below the dark line) and up into the air, where some end in spore-bearing heads. Scale bar 100 µm.' },
  'yeast-nucleus': { commons: 'File:Bakers yeast cytoplasm-nucleus.jpg', author: 'Tgru001', license: 'CC0', modality: 'Freeze-fracture EM',
    caption: 'Platinum replica of a freeze-fractured baker\'s yeast cell, showing the nucleus in its cytoplasm. Scale bar 0.1 µm.' },
  'hela-nucleoli': { commons: 'File:HeLa-Tubulin-HSP60-Fibrillarin-DNA.jpg', author: 'GerryShaw (EnCor Biotechnology)', license: 'CC BY-SA 4.0', modality: 'Fluorescence',
    caption: 'Human HeLa cells: nucleoli (red, fibrillarin) inside each nucleus (purple, DNA), with microtubules in green and mitochondria in yellow.' },
  'yeast-vacuoles': { commons: 'File:Yeast cells with vacuoles marked with Vph1-GF (16193318289).jpg', author: 'Henderson et al., eLife (2014)', license: 'CC BY 2.0', modality: 'Fluorescence',
    caption: 'Budding yeast whose vacuole membrane protein Vph1 is tagged with GFP: the bright compartments inside each cell are its vacuoles.' },
  'hela-mitochondria': { commons: 'File:HeLa mtGFP.tif', author: 'Simon Troeder', license: 'CC BY 4.0', modality: 'Fluorescence',
    caption: 'Human HeLa cells expressing mitochondria-targeted GFP. Yeast mitochondria form the same kind of branched tubular network, just under the cortex.' },
  'yeast-wall': { commons: 'File:Bakers yeast wall-membrane.jpg', author: 'Tgru001', license: 'CC0', modality: 'Freeze-fracture EM',
    caption: 'Freeze-fracture replica of baker\'s yeast at the wall–membrane boundary: the plasma membrane pressed against the wall, with its typical elongated furrows. Scale bar 0.1 µm.' },
  'yeast-sem': { commons: 'File:Saccharomyces cerevisiae SEM.jpg', author: 'Mogana Das Murtey and Patchamuthu Ramasamy', license: 'CC BY 3.0', modality: 'SEM',
    caption: 'Scanning electron micrograph of S. cerevisiae. The raised rings on the mothers are bud scars, one per daughter; some buds are still attached. Scale bar 5 µm.' },
  'yeast-septins': { commons: 'File:S cerevisiae septins.jpg', author: 'Philippsen Lab, Biozentrum Basel', license: 'Public domain', modality: 'Fluorescence',
    caption: 'S. cerevisiae with GFP-tagged septin (green) forming a collar at each mother–bud neck; cell outlines in red. Scale bar 10 µm.' },
  'yeast-dic': { commons: 'File:S cerevisiae under DIC microscopy.jpg', author: 'Masur', license: 'Public domain', modality: 'DIC',
    caption: 'Living S. cerevisiae in DIC microscopy (100× oil objective): single cells and mothers carrying small and large buds.' },
  'anaphase': { commons: 'File:Anaphase IF.jpg', author: 'Roy van Heesbeen', license: 'Public domain', modality: 'Fluorescence',
    caption: 'An animal cell in anaphase: chromosomes (blue) pulled apart by the spindle (green). Yeast mitosis is closed: the nuclear envelope stays intact and the whole nucleus stretches through the neck.' },
  'telophase': { commons: 'File:TelophaseIF.jpg', author: 'Roy van Heesbeen', license: 'Public domain', modality: 'Fluorescence',
    caption: 'An animal cell in telophase: two daughter nuclei (blue) re-forming either side of the spindle midzone (green).' },
  'spectrin': { commons: 'File:Spectrin localization under the neuronal plasme membrane..jpg', author: 'GerryShaw (EnCor Biotechnology)', license: 'CC BY-SA 3.0', modality: 'Confocal',
    caption: 'αII-spectrin (green) lining the membrane of cultured rat neurons; DNA in blue. Red cells carry their own spectrin in the same kind of net under the membrane.' },
  'rbc-light': { commons: 'File:Redbloodcells.jpg', author: 'Drs Noguchi, Rodgers and Schechter, NIDDK (NIH)', license: 'Public domain', modality: 'Light',
    caption: 'Human red blood cells in the light microscope. Each is packed with haemoglobin; the paler centre is the thin dimple.' },
  'rbc-sem-colour': { commons: 'File:Red White Blood cells.jpg', author: 'Electron Microscopy Facility, NCI-Frederick', license: 'Public domain', modality: 'SEM',
    caption: 'False-coloured scanning electron micrograph: a red blood cell with its central dimple, beside a platelet (yellow) and a white blood cell (blue).' },
  'rbc-sem': { commons: 'File:Red blood cells (2).jpg', author: 'Scootdive', license: 'CC BY-SA 3.0', modality: 'SEM',
    caption: 'Scanning electron micrograph of red blood cells, some tilted edge-on to show the thick rim around the thin middle. Scale bar 1.19 µm.' },
  'rbc-crenated': { commons: 'File:Crenated Red Cells.jpg', author: 'Osaretin', license: 'CC BY-SA 4.0', modality: 'Light',
    caption: 'A blood smear with crenated red cells (echinocytes), their edges scalloped into bumps, among normal smooth discs.' },
  'rbc-echinocytes': { commons: 'File:Scanning electron microscopy (SEM) of echinocytes.png', author: 'Geekiyanage N. M. et al.', license: 'CC BY 4.0', modality: 'SEM',
    caption: 'Scanning electron micrographs of echinocytes, from rounded bumps (left) to sharp spicules all over the cell (right). Scale bar 2 µm.' },
  'rbc-spherocyte': { commons: 'File:Red Blood Cells observed with scanning electron microscope (SEM). Left spherocyte. Right normal red blood cell.png', author: 'Joan-Lluis Vives-Corrons and Elena Krishnevskaya', license: 'CC BY 4.0', modality: 'SEM',
    caption: 'Scanning electron micrograph of a spherocyte (left) next to a normal biconcave red cell (right).' },
  'fibroblast-nucleus': { commons: 'File:MouseChromosomeTerritoriesBMC Cell Biol6-44Fig2e.jpg', author: 'Mayer R., Brero A., von Hase J., Schroeder T., Cremer T., Dietzel S.', license: 'CC BY 2.0', modality: 'Fluorescence',
    caption: 'The nucleus of a mouse fibroblast, DNA in blue, with chromosomes 2 (red) and 9 (green) painted by FISH: each chromosome keeps to its own territory.' },
  'focal-adhesions': { commons: 'File:Focaladhesion.jpg', author: 'Christoph Moehl (Pommesbude)', license: 'CC BY 2.5', modality: 'Fluorescence',
    caption: 'A fibroblast stained for vinculin (red) and actin (green). Adhesions begin as small dots at the edge and grow into these plaques at the ends of the stress fibres. Scale bar 20 µm.' },
  'focal-adhesion-detail': { commons: 'File:Focaladhesiondetail.jpg', author: 'Christoph Moehl (Pommesbude)', license: 'CC BY-SA 2.5', modality: 'Fluorescence',
    caption: 'Detail of a fibroblast: vinculin-rich focal adhesions (red) at the ends of actin stress fibres (green). Scale bar 10 µm.' },
  'fibroblast-mitochondria': { commons: 'File:Indian Muntjac fibroblast cells (24271618921).jpg', author: 'ZEISS Microscopy (sample: Michael W. Davidson, FSU)', license: 'CC BY 2.0', modality: 'Fluorescence',
    caption: 'Indian muntjac fibroblasts: mitochondria in red (MitoTracker) threaded among actin stress fibres (green, phalloidin); nuclei blue (DAPI). Scale bar 20 µm.' },
  'fibroblast-stress-fibres': { commons: 'File:Indian Muntjac fibroblast cells (24327908636).jpg', author: 'ZEISS Microscopy (sample: Michael W. Davidson, FSU)', license: 'CC BY 2.0', modality: 'Fluorescence',
    caption: 'Actin stress fibres (green, phalloidin) running the length of Indian muntjac fibroblasts; mitochondria red, nuclei blue. Scale bar 20 µm.' },
  'mef-actin': { commons: 'File:MEF microfilaments.jpg', author: 'Y tambe', license: 'CC BY-SA 3.0', modality: 'Fluorescence',
    caption: 'Actin filaments (green) in mouse embryonic fibroblasts spreading and pulling on their substrate. Scale bar 10 µm.' },
  'myofibroblast': { commons: 'File:Diferenciación de fibroblastos a miofibroblastos cardíacos 2x2.jpg', author: 'Leslye Venegas and Danica Jiménez', license: 'CC BY 4.0', modality: 'Phase contrast',
    caption: 'Cardiac fibroblasts in culture 0, 24, 48 and 72 h after TGF-β, the signal that turns them into myofibroblasts.' },
  'fibroblast-sem': { commons: 'File:Fibroblasts 1.jpg', author: 'Judyta Dulnik', license: 'CC BY-SA 4.0', modality: 'SEM',
    caption: 'Scanning electron micrograph of mouse fibroblasts on an electrospun nanofibre scaffold: some still rounded, others spreading thin membrane over the fibres. Scale bar 10 µm.' },
  'lamellipodium': { commons: 'File:Lamellipodium.png', author: 'Yang T. D. et al.; Alexandre Saez', license: 'CC BY-SA 3.0', modality: 'Phase contrast',
    caption: 'A crawling cell in phase contrast, with thin lamellipodia at its leading edge (green arrows), and sketches of the crawling cycle (right). Scale bar 50 µm.' },
  'microglia-iba1': { commons: 'File:Microglial cells.tif', author: 'J. Wegiel', license: 'CC BY 4.0', modality: 'Fluorescence',
    caption: 'Microglia (red, IBA1) scattered through brain tissue; DNA in blue marks every nucleus.' },
  'phagocytosis': { commons: 'File:Phagocytosis of a Dead Yeast Particle (6830921067).jpg', author: 'NIAID', license: 'CC BY 2.0', modality: 'SEM',
    caption: 'False-coloured scanning electron micrograph of a phagocyte (grey) wrapping a dead yeast particle (zymosan, gold). Engulfed debris like this ends up in a phagolysosome.' },
  'microglia-ramified': { commons: 'File:Microglial cells (red) in rat cerebellar molecular layer.jpg', author: 'GerryShaw (EnCor Biotechnology)', license: 'CC BY-SA 4.0', modality: 'Fluorescence',
    caption: 'Ramified microglia (red, IBA-1) in the molecular layer of the rat cerebellum, their thin processes reaching out between other cells; nuclei blue.' },
  'microglia-lps': { commons: 'File:LPS induces microglia activation in vitro.png', author: 'da Silveira Cruz-Machado S. et al.', license: 'CC BY 4.0', modality: 'Light',
    caption: 'Immunostained microglia without (left, ramified, arrows) and with the bacterial toxin LPS (right, arrowheads): activated, they pull in their processes and round up.' },
  'macrophages-lectin': { commons: 'File:Makrofagi 2.jpg', author: 'Grzegorz Wicher', license: 'Public domain', modality: 'Light',
    caption: 'Lectin-stained (brown) macrophages in injured rat cortex: round cells with short, stubby extensions. Activated microglia take this amoeboid form.' },
  'mitochondrion-cryo': { commons: 'File:MitochondrionCAM.jpg', author: 'Carmmann (Wadsworth Center)', license: 'Public domain', modality: 'Cryo-ET',
    caption: 'A frozen-hydrated rat liver mitochondrion reconstructed by electron tomography: the cristae are tubular invaginations of the inner membrane.' },
  'microglia-lectin': { commons: 'File:Mikroglej 1.jpg', author: 'Grzegorz Wicher', license: 'Public domain', modality: 'Light',
    caption: 'Ramified microglia stained with lectin (brown). Each fine process ends in a tip that samples its surroundings.' },
  'neuron-nissl': { commons: 'File:Nissl bodies in neurons of the spinal cord.jpg', author: 'Tulemo', license: 'CC BY-SA 4.0', modality: 'Light',
    caption: 'Motor neurons in the spinal cord (cresyl violet and luxol fast blue): purple Nissl bodies (arrows) crowd the cytoplasm around a pale nucleus with a dark nucleolus. Scale bar 30 µm.' },
  'neuron-nucleoli': { commons: 'File:38F3-ChkNFH-DAPI-Shsy5y.jpg', author: 'GerryShaw (EnCor Biotechnology)', license: 'CC BY-SA 4.0', modality: 'Fluorescence',
    caption: 'Human SH-SY5Y neuroblastoma cells: nucleoli (green, fibrillarin) inside the nuclei (blue, DAPI); neurofilament NF-H in red.' },
  'axon-initial-segment': { commons: 'File:MBP-Ank3-Rat-Cerebral-Cortex.jpg', author: 'GerryShaw (EnCor Biotechnology)', license: 'CC BY-SA 4.0', modality: 'Confocal',
    caption: 'Rat cerebral cortex. Ankyrin-G (red) marks axon initial segments, the stretch just past the hillock where spikes start; myelin in green (MBP), nuclei in blue. Scale bar 20 µm.' },
  'dendritic-spines': { commons: 'File:Dendritic spines.jpg', author: 'Tmhoogland', license: 'Public domain', modality: 'Two-photon',
    caption: 'A dendrite of a striatal medium spiny neuron expressing EGFP, studded with spines, each a site of synaptic input. Scale bar 1 µm.' },
  'axon-mitochondria': { commons: 'File:Mitocondria Axon Presinaptico.PNG', author: 'Fischer T. D., Dash P. K., Liu J., Waxham M. N.', license: 'CC BY 4.0', modality: 'Cryo-ET',
    caption: 'Cryo-electron tomogram of a presynaptic swelling on an axon (left) and its 3D segmentation (right): mitochondria (green), microtubules, ER and vesicles.' },
  'myelinated-axon': { commons: 'File:Myelinated neuron.jpg', author: 'Electron Microscopy Facility, Trinity College (uploaded by Roadnottaken)', license: 'CC BY-SA 3.0', modality: 'TEM',
    caption: 'Transmission electron micrograph of an axon in cross-section, wrapped in compact myelin, with a mitochondrion inside. Scale bar 500 nm.' },
  'nmj-terminal': { commons: 'File:Electron micrograph of neuromuscular junction (cross-section).jpg', author: 'National Institute of Mental Health', license: 'Public domain', modality: 'TEM',
    caption: 'Electron micrograph of a neuromuscular junction: the axon terminal (T), full of synaptic vesicles, over a muscle fibre (M) with its junctional folds (arrow). Scale bar 0.3 µm.' },
  'wallerian': { commons: 'File:Wallerian degeneration in cut and crushed PNS nerve.jpg', author: 'Beirowski B. et al.', license: 'CC BY 2.0', modality: 'Fluorescence',
    caption: 'Fluorescent axons in a cut or crushed peripheral nerve, 37–44 h after the injury: intact at first, then broken into fragments (Wallerian degeneration).' },
  'growth-cone': { commons: 'File:Growthcone.jpg', author: 'Paul Letourneau, University of Minnesota (via NIH)', license: 'Public domain', modality: 'Fluorescence',
    caption: 'The growth cone of an elongating axon: actin (red) fills the filopodia and lamellipodium; microtubules (green) run up the axon shaft.' },
  'pombe-division': { commons: 'File:Schizosaccharomyces pombe division.JPG', author: 'Roland Gromes', license: 'CC BY-SA 3.0', modality: 'Light',
    caption: 'Fission yeast in bright field (left) and dark field (right): a single cell (top), a cell with its septum across the middle, and two daughters that have just parted, their new ends facing each other.' },
  'pombe-calcofluor': { commons: 'File:Fission yeast division.jpg', author: 'Liam Pennington (G Lens Microscopist)', license: 'CC BY 4.0', modality: 'Confocal',
    caption: 'Fission yeast stained with calcofluor white, which binds cell wall. From top to bottom: a growing cell, a bright septum across the middle, the septum splitting, and two separate daughters.' },
  'pombe-tem': { commons: 'File:Schizosaccharomyces pombe tsentrosoom.jpg', author: 'Tiina Tamm', license: 'CC BY-SA 3.0', modality: 'TEM',
    caption: 'Thin sections of fission yeast. Left: a whole cell inside its wall, with the nucleus in the middle. Centre and right: the nucleus within its intact envelope; the dark plaque on the envelope is the spindle pole body, the yeast centrosome. Scale bars 500 nm.' },
  'pombe-timelapse': { commons: 'File:Gene Function in the Fission Yeast Schizosaccharomyces pombe.png', author: 'Aharrell12345', license: 'CC BY 4.0', modality: 'Fluorescence',
    caption: 'Living fission yeast in late anaphase and early cytokinesis, frame by frame: microtubules in green (tubulin Atb2-GFP), running the length of the cells, and the contractile ring in red (myosin light chain Rlc1) across the middle of the dividing one.' },
  'ecoli-sem': { commons: 'File:E. coli Bacteria (7316101966).jpg', author: 'NIAID', license: 'Public domain', modality: 'SEM',
    caption: 'Scanning electron micrograph of E. coli grown in culture on a cover slip. What is seen is the outer membrane, the outermost of the envelope\'s three layers. Scale bar 2 µm.' },
  'ecoli-dividing': { commons: 'File:Ecoli dividing.jpg', author: 'CDC / Evangeline Sowers, Janice Haney Carr', license: 'Public domain', modality: 'SEM',
    caption: 'Scanning electron micrograph of an E. coli cell at the end of division: the two daughters are still joined where their new poles have just closed. Scale bar 1 µm.' },
  'ecoli-flagella': { commons: 'File:Escherichia coli flagella TEM.png', author: 'CDC / E. H. White, Peggy S. Hayes', license: 'Public domain', modality: 'TEM',
    caption: 'Transmission electron micrograph (colourised) of an E. coli O157:H7 cell with its flagella: helical filaments several times longer than the cell, each turned by a motor in the envelope.' },
  'nucleoid-ellipsoid': { commons: 'File:Subhash nucleoid 11.png', author: 'Verma S. C., Qian Z., Adhya S. L. (PLoS Genet 2019)', license: 'CC BY 4.0', modality: 'Fluorescence',
    caption: 'The E. coli nucleoid. A: a drawing of its curved, lobed shape inside the cell. B: DNA density measured in a living cell from the fluorescence of the DNA-binding protein HU-mCherry, shown in section (blue low, red high). Scale 250 nm.' },
  'centrosome-golgi': { commons: 'File:Regrowth of microtubules from a centrosome and Golgi apparatus in vitro.jpg', author: 'Brian6122', license: 'CC BY 4.0', modality: 'Confocal',
    caption: 'Microtubules (red) growing back from the centrosome, the bright pair of dots at the centre, and from the Golgi membranes gathered around it (spinning-disk confocal).' },
  'golgi-tem': { commons: 'File:GolgilTGNc.jpg', author: 'JeanOhm, from a micrograph by Louisa Howard', license: 'CC BY-SA 4.0', modality: 'TEM',
    caption: 'Transmission electron micrograph of the Golgi apparatus of a human leukocyte: a curved stack of flat cisternae, with the trans-Golgi network (TGN) and its vesicles on the concave side. Scale bar 100 nm.' },
};

/** Which image each label shows, by "cell:Label name" first, then by name alone; a caption here replaces the image's own. */
const LABELS: Record<string, string | { pic: string; caption: string }> = {
  // yeast
  'yeast:Nucleus': 'yeast-nucleus',
  'yeast:Nucleolus': { pic: 'hela-nucleoli', caption: 'Nucleoli (red, fibrillarin) in human HeLa cells. In yeast the nucleolus is a single crescent against the nuclear envelope, marked by the same protein (called Nop1 there).' },
  'yeast:Mitochondria': 'hela-mitochondria',
  'Vacuole': 'yeast-vacuoles',
  'Cell wall': 'yeast-wall',
  'Bud scar': 'yeast-sem',
  'Septin ring': 'yeast-septins',
  'Bud (daughter)': 'yeast-dic',
  'Anaphase bridge': 'anaphase',
  'Daughter nucleus': 'telophase',
  'yeast:Spindle': { pic: 'anaphase', caption: 'A spindle (green) pulling chromosomes (blue) apart in an animal cell. The yeast spindle does the same job inside the intact nucleus, between two spindle pole bodies set in the envelope.' },
  'yeast:Contractile ring': { pic: 'yeast-septins', caption: 'The septin collar (green) at each mother–bud neck of S. cerevisiae. The myosin ring lies just inside the collar and contracts between its two halves at cytokinesis. Scale bar 10 µm.' },
  'yeast:Septum': { pic: 'yeast-sem', caption: 'Scanning electron micrograph of S. cerevisiae. The raised rings on the mothers are bud scars: what is left of the chitin septum after each daughter has gone. Scale bar 5 µm.' },
  // fission yeast
  'pombe:Nucleus': 'pombe-tem',
  'pombe:Nucleolus': { pic: 'hela-nucleoli', caption: 'Nucleoli (red, fibrillarin) in human HeLa cells. The fission yeast nucleolus is marked by the same protein and fills one side of the nucleus.' },
  'pombe:Mitochondria': { pic: 'hela-mitochondria', caption: 'Human HeLa cells expressing mitochondria-targeted GFP. Fission yeast mitochondria are tubules of the same kind, laid along the long axis of the cell beside the microtubules.' },
  'pombe:Cell wall': { pic: 'pombe-calcofluor', caption: 'Fission yeast stained with calcofluor white, which binds cell wall: the outline of each cell is its wall, and the brightest wall is the new septum.' },
  'Vacuoles': { pic: 'yeast-vacuoles', caption: 'Vacuole membranes (Vph1-GFP) in budding yeast, which has one or a few large vacuoles per cell. Fission yeast has many small ones instead.' },
  'Birth scar': { pic: 'pombe-calcofluor', caption: 'Fission yeast stained with calcofluor white. After the septum has split (bottom), each daughter keeps a ridge where it met the side wall: the birth scar, at the base of her new end.' },
  'Microtubule bundle': 'pombe-timelapse',
  'Old end': 'pombe-division',
  'New end': 'pombe-division',
  'pombe:Spindle': { pic: 'pombe-tem', caption: 'Thin sections of fission yeast. The dark plaque on the nuclear envelope (centre and right) is the spindle pole body. In mitosis it duplicates, and the spindle forms between the two inside the nucleus. Scale bars 500 nm.' },
  'Contractile ring': 'pombe-timelapse',
  'Septum': 'pombe-calcofluor',
  'New cell ends': 'pombe-division',
  // E. coli
  'Nucleoid': 'nucleoid-ellipsoid',
  'Cell envelope': 'ecoli-sem',
  'Ribosome-rich cytoplasm': { pic: 'nucleoid-ellipsoid', caption: 'DNA density in a living E. coli cell (B: blue low, red high). Ribosomes fill what the nucleoid leaves free: the two ends of the cell, the middle between the lobes, and a shell under the membrane.' },
  'Chemoreceptor array': { pic: 'ecoli-flagella', caption: 'An E. coli O157:H7 cell and its flagella (colourised TEM). The receptor arrays at the poles decide which way the flagellar motors turn, and so whether the cell keeps swimming or tumbles.' },
  'Cell pole': 'ecoli-flagella',
  'Z ring': { pic: 'ecoli-dividing', caption: 'An E. coli cell at the end of division (SEM). The furrow between the daughters is where the Z ring assembled, under the membrane, about 20 minutes earlier. Scale bar 1 µm.' },
  'Constriction': 'ecoli-dividing',
  'New poles': 'ecoli-dividing',
  // red blood cell
  'Membrane skeleton': 'spectrin',
  'Haemoglobin': 'rbc-light',
  'Central dimple': 'rbc-sem-colour',
  'Rim': 'rbc-sem',
  'Crenation': 'rbc-crenated',
  'Spicule': 'rbc-echinocytes',
  'Spherical shape': 'rbc-spherocyte',
  // fibroblast
  'fibroblast:Nucleus': 'fibroblast-nucleus',
  'fibroblast:Nucleolus': { pic: 'hela-nucleoli', caption: 'Nucleoli (red, fibrillarin) in human HeLa cells, several per nucleus (purple), as in fibroblasts.' },
  'fibroblast:Mitochondria': 'fibroblast-mitochondria',
  'Nascent adhesion': 'focal-adhesions',
  'Focal adhesion': 'focal-adhesion-detail',
  'Stress fibre': 'fibroblast-stress-fibres',
  'Radial fibre': 'mef-actin',
  'α-SMA stress fibre': 'myofibroblast',
  'Spreading skirt': 'fibroblast-sem',
  'Spreading edge': 'lamellipodium',
  'Lamellipodium': 'lamellipodium',
  'Golgi apparatus': 'golgi-tem',
  'Centrosome': 'centrosome-golgi',
  'Trailing edge': { pic: 'lamellipodium', caption: 'A crawling cell in phase contrast: lamellipodia lead at the front (green arrows) while a long tail trails behind, still anchored until its adhesions let go. Scale bar 50 µm.' },
  // microglia
  'microglia:Nucleus': 'microglia-iba1',
  'microglia:Mitochondria': 'mitochondrion-cryo',
  'Phagolysosome': 'phagocytosis',
  'Ramified process': 'microglia-ramified',
  'Retracting process': 'microglia-lps',
  'Pseudopod': 'macrophages-lectin',
  'Process tip': 'microglia-lectin',
  // neuron
  'neuron:Nucleus': 'neuron-nissl',
  'neuron:Nucleolus': 'neuron-nucleoli',
  'neuron:Mitochondria': 'axon-mitochondria',
  'Nissl body': 'neuron-nissl',
  'Axon hillock': 'axon-initial-segment',
  'Dendrite': 'dendritic-spines',
  'Axon': 'myelinated-axon',
  'Axon terminal': 'nmj-terminal',
  'Axon stump': 'wallerian',
  'Retraction bulb': { pic: 'wallerian', caption: 'After a cut, the part of the axon cut off from the cell body fragments within two days (fluorescent axons, 37–44 h after injury). The part still joined to the soma survives and seals into a retraction bulb (not shown).' },
  'Growth cone': 'growth-cone',
  // animal cell
  'animal:Nucleus': 'club-cell-tem',
  'animal:Nucleolus': 'club-cell-tem',
  'animal:Mitochondria': { pic: 'hela-mitochondria', caption: 'Human HeLa cells expressing mitochondria-targeted GFP: the mitochondria of an animal cell are a branching network of tubes, not separate beans.' },
  'Rough ER': 'rough-er',
  'Lysosome': { pic: 'phagocytosis', caption: 'A macrophage engulfing a dead yeast cell (scanning electron micrograph). What a cell swallows ends up in a lysosome, where it is digested; the lysosomes themselves are inside and not visible here.' },
  'Peroxisome': 'peroxisomes',
  'Plasma membrane': 'cell-membranes-tem',
  // plant cell
  'Chloroplast': 'chloroplast-tem',
  'Central vacuole': 'elodea-cells',
  'plant:Cell wall': 'moss-chloroplasts',
  'plant:Nucleus': { pic: 'club-cell-tem', caption: 'An animal cell in thin section (a secretory cell of the lung): its nucleus, with a dark nucleolus, at lower right. A plant nucleus is built the same way.' },
  'plant:Rough ER': { pic: 'rough-er', caption: 'Rough ER in an animal cell (pancreas), in thin section: parallel ribosome-studded sheets beside the nucleus. Plant ER looks the same. Scale bar 500 nm.' },
  'Golgi stack': { pic: 'golgi-tem', caption: 'A Golgi stack in an animal cell (a human white blood cell), in thin section. A plant cell has many small separate stacks of the same build.' },
  'plant:Mitochondria': { pic: 'mitochondrion-cryo', caption: 'A single mitochondrion reconstructed by electron tomography (from an animal cell): the inner membrane folds into cristae. Plant mitochondria are built the same way.' },
  'plant:Peroxisome': { pic: 'peroxisomes', caption: 'Peroxisomes in animal cells (rat heart muscle), stained for a peroxisomal membrane protein. In a leaf cell they sit against the chloroplasts.' },
  'Palisade cell': 'palisade-sem',
  // Aspergillus hypha
  'Hyphal tip': 'aspergillus-tip',
  'Spitzenkörper': 'aspergillus-tip',
  'aspergillus:Septum': 'aspergillus-septate',
  'aspergillus:Nucleus': { pic: 'aspergillus-septate', caption: 'Septate hyphae of an Aspergillus (lactophenol cotton blue). Each stretch between two septa holds several nuclei, which this stain does not pick out.' },
  'Woronin body': { pic: 'aspergillus-septate', caption: 'Septate hyphae of an Aspergillus (lactophenol cotton blue). The Woronin bodies sit beside the pore of each septum and are too small to see in the light microscope.' },
  'aspergillus:Vacuole': { pic: 'yeast-vacuoles', caption: 'Vacuole membranes (Vph1-GFP) in budding yeast, another fungus. In a hypha the vacuoles are small near the tip and large further back.' },
  'aspergillus:Mitochondria': { pic: 'hela-mitochondria', caption: 'Mitochondria as a network of tubes, here in human HeLa cells expressing mitochondria-targeted GFP. In a hypha the tubes lie along its length.' },
  'aspergillus:Cell wall': 'aspergillus-mycelium',
  // bacteriophage T4
  'Head': 't4-shadowed',
  'DNA genome': { pic: 't4-field', caption: 'Purified phages in negative stain; those marked 1 are T4. The DNA is packed inside each head and cannot be seen from outside. Scale bar 200 nm.' },
  'Tail sheath': 't4-em',
  'Tail tube': { pic: 't4-em', caption: 'A T4 particle in negative stain. The tube runs hidden inside the striated sheath, from the head to the baseplate.' },
  'Baseplate': 't4-em',
  'Long tail fibre': 't4-em',
  'Fibre joint': 't4-shadowed',
  // coronavirus
  'Spike': 'sars2-virions',
  'Envelope': 'sars2-virions',
  'RNA genome': 'sars2-cell',
  'Virion': 'sars2-cell',
};

/** The micrograph for a label of a cell type, or undefined if it has none. */
export function micrograph(cell: CellTypeId, name: string): Micrograph | undefined {
  const entry = LABELS[`${cell}:${name}`] ?? LABELS[name];
  if (!entry) return undefined;
  const key = typeof entry === 'string' ? entry : entry.pic;
  const pic = PICS[key];
  return pic && { ...pic, src: `micrographs/${key}.jpg`, ...(typeof entry === 'string' ? {} : { caption: entry.caption }) };
}

/** Commons page of a file, and the deed of its licence. */
export function commonsPage(m: Micrograph): string {
  return `https://commons.wikimedia.org/wiki/${encodeURIComponent(m.commons.replace(/ /g, '_'))}`;
}
export function licenseUrl(m: Micrograph): string | undefined {
  const cc = /^CC BY(-SA)? ([0-9.]+)$/.exec(m.license);
  if (cc) return `https://creativecommons.org/licenses/by${cc[1] ? '-sa' : ''}/${cc[2]}/`;
  if (m.license === 'CC0') return 'https://creativecommons.org/publicdomain/zero/1.0/';
  return undefined;
}
